In [3]:
 ### El mÃ©todo random forest selecciona de manera aleatoria observaciones del df, y de igual manera, deja deliberadamente fuera
  #de la base de datos otras. 
        # arboles de clasif o regres pero pluralizado en cientos o miles
        # los resultados de sus modelos permiten obtener:
            # la media en caso de variab numerics
            # la categoria con mas casos

from sklearn import tree
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier

inpath = "D:/Disco D/Big Data/Data/"
df = pd.read_csv(inpath + "base_datos_2008.csv")
df = df.dropna(subset = ["ArrDelay"]) 
df = df.sample(frac=1)
df = df.head(100000)
df_test = df.tail(100000)
df

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
2960796,2008,5,15,4,1108.0,1055,1353.0,1351,CO,1410,...,7.0,12.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3499549,2008,6,29,7,2022.0,1840,2358.0,2230,AA,1286,...,7.0,17.0,0,NaN,0,88.0,0.0,0.0,0.0,0.0
6600966,2008,12,25,4,1736.0,1737,1914.0,1919,NW,1688,...,7.0,18.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
609106,2008,2,3,7,1607.0,1545,1948.0,1930,WN,1109,...,4.0,18.0,0,NaN,0,0.0,0.0,12.0,0.0,6.0
5640190,2008,10,19,7,1450.0,1452,1617.0,1616,US,355,...,3.0,14.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1399958,2008,3,27,4,1338.0,1325,1637.0,1628,UA,83,...,3.0,18.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1289728,2008,3,31,1,1524.0,1455,1634.0,1615,XE,2566,...,7.0,11.0,0,NaN,0,0.0,0.0,0.0,0.0,19.0
3229158,2008,6,23,1,1656.0,1650,1819.0,1809,UA,451,...,21.0,16.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3588263,2008,6,7,6,552.0,600,745.0,804,DL,343,...,5.0,16.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5160891,2008,9,1,1,701.0,702,915.0,924,FL,876,...,5.0,9.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [4]:
clf =tree.DecisionTreeClassifier() #otros param max_features = nÂ°, bootstrap = boolean --> realiza muestreo con reemplazo
                                                                    # generando muestras aleatorias de las filas para rehacer los 
                                                                    # bosques

x = df[["AirTime", "Distance", "TaxiIn", "TaxiOut", "DepTime", "DepDelay"]]
x_test = df_test[["AirTime", "Distance", "TaxiIn", "TaxiOut", "DepTime", "DepDelay"]]
y = df["ArrDelay"] > 10
y_test = df_test["ArrDelay"] > 10 # variable respuesta, booleana

clf = clf.fit(x,y)
y_pred_test = clf.predict(x_test)
np.mean(y_test == y_pred_test)

1.0

In [7]:
clf = RandomForestClassifier(n_estimators = 100) #esta generando 100 arboles
clf.fit(x,y)
y_pred_test = clf.predict(x_test)

clf.feature_importances_ # nos da la reelevancia de las variables usadas, em el caso de abajo, la mas relevante es Depdelay

array([0.07637332, 0.0852916 , 0.05414406, 0.13689945, 0.07973329,
       0.56755828])

In [8]:
np.mean(y_test == y_pred_test)

0.99999

In [ ]:
# RandomForestRegressor() #para arboles de regresion, se usa igual